print("Here is a quiz to see which power ranger you are")

print("Question 1")
print("What animal do you like most?")
print("a.Tyrannosaurus")
print("b.Triceratops")
print("c.Saber-Toothed Tiger")
print("d.Pterodactyl")
if answer1 =="A,B,C,D":
    score = score+1
# Ask the question and get an answer  
print("Question 2")
print("Which color do you like best out of this list?")
print("a.Blue")
print("b.Red")
print("c.Yellow")
print("d.Pink")

print("Question 3")
print("Which childhood show do you like from the list?")
print("a.Rocket Power")
print("b.Power Rangers")
print("c.Spongebob Squarepants")
print("d.Barney")

print("Question 4")
print("Which place would you go to on vacation?")
print("a.Hawaii")
print("b.Bahamas")
print("c.Florida")
print("d.California")
print()
print("Question 5")
print("Favorite car brand?")
print("a.Ford")
print("b.Nissan")
print("c.BMW")
print("d.Honda")
print()
print("Question 6")
print("Favorite genre of music")
print("a.Rap")
print("b.Rock")
print("c.Country")
print("d.EDM")
print()
print("Question 7")
print("Favorite subject in school")
print("a.Math")
print("b.Gym")
print("c.History")
print("d.Art")
print()
print("Question 8")
print("Favorite movie series")
print("a.Transformers")
print("b.Twilight")
print("c.Fast and the Furious")
print("d.Spider Man")
print()
print("Question 9")
print("Favorite super hero")
print("a.Thor")
print("b.Ant man")
print("c.The Flash")
print("d.Iron Man")
print()
print("Question 10")
print("Favorite sport")
print("a.Soccer")
print("b.Basketball")
print("c.Hockey")
print("d.Baseball")

input("\nPress the enter key to exit.")
